module.exports = {
  "PERMISSIONS_ADMINISTRATOR": "Administrator",
  "PERMISSIONS_CREATE_INSTANT_INVITE": "Criar convites instantâneos",
  "PERMISSIONS_KICK_MEMBERS": "Expulsar membros",
  "PERMISSIONS_BAN_MEMBERS": "Banir membros",
  "PERMISSIONS_MANAGE_CHANNELS": "Gerenciar canais",
  "PERMISSIONS_MANAGE_GUILD": "Gerenciar servidor",
  "PERMISSIONS_ADD_REACTIONS": "Adicionar reações",
  "PERMISSIONS_VIEW_AUDIT_LOGS": "Ver Registro de Auditoria",
  "PERMISSIONS_PRIORITY_SPEAKER": "Voz Prioritária",
  "PERMISSIONS_VIEW_CHANNEL": "Ver canal",
  "PERMISSIONS_SEND_MESSAGES": "Enviar mensagens",
  "PERMISSIONS_SEND_TTS_MESSAGES": "Enviar mensagens tts (text to speech)",
  "PERMISSIONS_MANAGE_MESSAGES": "Gerenciar mensagens",
  "PERMISSIONS_EMBED_LINKS": "Inserir links",
  "PERMISSIONS_ATTACH_FILES": "Anexar arquivos",
  "PERMISSIONS_READ_MESSAGE_HISTORY": "Ver histórico de mensagens",
  "PERMISSIONS_MENTION_EVERYONE": "Mencionar todos",
  "PERMISSIONS_USE_EXTERNAL_EMOJIS": "Usar emojis externos",
  "PERMISSIONS_CONNECT": "Conectar em um canal de voz",
  "PERMISSIONS_SPEAK": "Falar em um canal de voz",
  "PERMISSIONS_MUTE_MEMBERS": "Mutar membros",
  "PERMISSIONS_DEAFEN_MEMBERS": "Ensurdecer membros",
  "PERMISSIONS_MOVE_MEMBERS": "Mover membros",
  "PERMISSIONS_USE_VAD": "Usar detecção de voz",
  "PERMISSIONS_CHANGE_NICKNAME": "Mudar apelido",
  "PERMISSIONS_MANAGE_NICKNAMES": "Gerenciar apelidos",
  "PERMISSIONS_MANAGE_ROLES": "Gerenciar cargos",
  "PERMISSIONS_MANAGE_WEBHOOKS": "Gerenciar webhooks",
  "PERMISSIONS_MANAGE_EMOJIS": "Gerenciar emojis",
  "PERMISSIONS_MEMBER_NO_PERM": "{0}, Você não tem permissão (``{1}``) para executar esse comando!",
  "PERMISSIONS_CLIENT_NO_PERM": "{0}, Desculpe, eu não tenho permissão (``{1}``) para poder executar esse comando! <:hikanipout:649034622470193172>",
  "PING_RESPONSES": [`Eu consegui? Eu cheguei à tempo?`, `Sério? Eu gastei {0}ms com você...`],
  "PING_BOT_LATENCY": "Latência do bot",
  "PING_API_LATENCY": "Latência da API do Discord"
};